giantswarm/cluster-gcp

helm/cluster-gcp/values.yaml

* Move from `n1-standard-2` with 2 vCPU and 7Gbi to `n2-standard-4` with 4 vCPU and 16Gbi. Otherwise there is not enough CPU for everything deployed on an MC
* Bump control-plane nodes to 3 and worker nodes to 4, to be more alinged with AWS and Azure MCs

Bump default node count and instance types

---

CHANGELOG.md
helm/cluster-gcp/templates/_machine_deployments.tpl

The document separator at the end of the KubeadmConfigTemplate is needed, otherwise helm 
generates only a single KubeadmConfigTemplate with the last machineDeployment's name.

Fix machine deployments range

---

CHANGELOG.md
helm/cluster-gcp/templates/_helpers.tpl

CI was complaining because of missing team label, so let's add it https://app.circleci.com/pipelines/github/giantswarm/cluster-gcp/99/workflows/03e0ce1d-9673-4cb5-9f8d-05dec31d3054/jobs/99

Add team label to helm resources

---

CHANGELOG.md
helm/cluster-gcp/templates/_control_plane.tpl
helm/cluster-gcp/values.schema.json
helm/cluster-gcp/values.yaml

Currently, by default, the Compute Engine default service account is assigned to all the VM instances (looks something like `<project-id-number>-compute@developer.gserviceaccount.com `. That one might not have any permissions though. The `service-controller` on the control plane uses this service account to create LoadBalancer ServiceAccounts (the kubernetes kind this time).
This change makes it so that we can specify the service account (the gcp kind) on the control plane nodes and control what permissions it has.

Add ServiceAccount to control-plane MachineTemplate

---

CHANGELOG.md
helm/cluster-gcp/templates/_control_plane.tpl
helm/cluster-gcp/values.schema.json
helm/cluster-gcp/values.yaml

By default the instance will receive no scopes, which means it won't be
able to do anything.
We only need the Compute scope.
See [gcloud docs --scopes flag](https://cloud.google.com/sdk/gcloud/reference/compute/instances/create) for list of scopes

Add the compute-rw scope

---

CHANGELOG.md
helm/cluster-gcp/files/etc/kubernetes/gcp.conf
helm/cluster-gcp/templates/_control_plane.tpl
helm/cluster-gcp/templates/_helpers.tpl

- Add `cloud-config` for GCP cloud provider to enable multizone for controller manager.

add-cloud-config

---

CHANGELOG.md
helm/cluster-gcp/templates/_gcp_cluster.tpl
helm/cluster-gcp/values.schema.json
helm/cluster-gcp/values.yaml

When passing several failure domains, these get rendered on the `App` as
```
failureDomains: [europe-west3-a europe-west3-b]
```
which gets rendered in the `GCPCluster` as 
```
spec:
controlPlaneEndpoint:
host: ""
port: 0
failureDomains:
- europe-west3-a europe-west3-b europe-west3-c
```
This is a single value `europe-west3-a europe-west3-b europe-west3-c` instead of an array.

Render failure domains as an array

---

CHANGELOG.md
helm/cluster-gcp/templates/_gcp_cluster.tpl
helm/cluster-gcp/templates/_machine_deployments.tpl

To avoid issues with the `zone` being wrong we should block the chart from rending with incorrect values provided.

Prevent setting failureDomain not in region

---

CHANGELOG.md
Makefile.gen.app.mk
helm/cluster-gcp/templates/_bastion.tpl
helm/cluster-gcp/templates/_control_plane.tpl
helm/cluster-gcp/templates/_gcp_cluster.tpl
helm/cluster-gcp/templates/_machine_deployments.tpl
helm/cluster-gcp/values.schema.json
helm/cluster-gcp/values.yaml

Allows for custom subnets to be provided instead of the auto-generated. Also adds the ability to specify the subnet that machinedeployments are put into.
Fixes https://github.com/giantswarm/roadmap/issues/1144 
Chores:
* Fixed gen-schema make task.
* Removed `label=default` example machine label (and updated template to make it optional without a trailing `,`)

Support custom subnets

---

CHANGELOG.md
helm/cluster-gcp/files/opt/init-disks.sh
helm/cluster-gcp/templates/_control_plane.tpl
helm/cluster-gcp/templates/_machine_deployments.tpl
helm/cluster-gcp/values.schema.json
helm/cluster-gcp/values.yaml

add additional disks for the control plane nodes ( disk for containerd, kubelet and etcd)
add additional disks for the worker nodes (disk  for contained, kubelet)
to align with vintage and CAPA

add-disk-for-control-plane

---

CHANGELOG.md
helm/cluster-gcp/templates/_bastion.tpl
helm/cluster-gcp/templates/_machine_deployments.tpl

`MachineSets` created by `MachineDeployments` are not labeled with common labels.

Add labels to MachineSets

---

CHANGELOG.md
helm/cluster-gcp/templates/_machine_deployments.tpl
helm/cluster-gcp/values.schema.json
helm/cluster-gcp/values.yaml

Our UIs (happa, kubectl-gs) will show a description of the nodepool, which is a free text that customers can set as an annotation. We need to allow to set that value.

Allow to set nodepool description

---

CHANGELOG.md
Makefile.custom.mk
helm/cluster-gcp/ci/ci-values.yaml
helm/cluster-gcp/templates/_gcp_cluster.tpl
helm/cluster-gcp/values.yaml

- Updated Kubernetes version to `v1.22.10`
- Switched Ubuntu version to `2004`
- Made GCP Project ID required (and defaulted to "")

Updated kubernetes and ubuntu version

---

CHANGELOG.md
helm/cluster-gcp/templates/_control_plane.tpl
helm/cluster-gcp/values.schema.json
helm/cluster-gcp/values.yaml

etcd 3.5.0 (the current kubeadm default) has a known issue and not recommended for production (see https://github.com/etcd-io/etcd/releases/tag/v3.5.0)
This change bumps the version to the latest available and makes it configurable via helm values.

Bump etcd version and make configurable

---

CHANGELOG.md
helm/cluster-gcp/templates/_gcp_cluster.tpl

When passing `nodeSubnetCidrs` and `autoCreateSubnetworks: false`  the k8s api complains with
```
The GCPCluster "test-jose" is invalid: spec.network.subnets.routeTableId: Invalid value: "null": spec.network.subnets.routeTableId in body must be of type boolean: "null"
```
This is because [the field is defined as](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/d6458338fb1fa03f87bbc1b6c2e35706c8e5264c/api/v1beta1/types.go#L150)
```
EnableFlowLogs *bool `json:"routeTableId"`
```
so it's a pointer to a boolean. Hence when no set, its value is null. But the openapi schema [defines the field as bool](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/v1.1.1/config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml#L581-L586), and in openAPI
> type: …

Set routeTableId: false when passing 'nodeSubnetCidrs

---

CHANGELOG.md
helm/cluster-gcp/templates/_control_plane.tpl

components deployed by `kubeadm` can't be accessed by prometheus

Expose metrics from components installed by kubeadm

---

CHANGELOG.md
helm/cluster-gcp/templates/_control_plane.tpl
helm/cluster-gcp/templates/_machine_deployments.tpl

Towards https://github.com/giantswarm/roadmap/issues/1145
In our vintage product we are deploying certificates to `/etc/kubernetes/ssl` directory, so cert-exporter expects them to be there.
This PR aligns CAPI WCs with vintage WCs:
- Set certificates directory to `/etc/kubernetes/ssl` in KubeadmControlPanel and KubeadmConfigTemplate `clusterConfiguration`.
- Set CA certificate path to `/etc/kubernetes/ssl/ca.crt` in KubeadmControlPanel and KubeadmConfigTemplate `joinConfiguration`.

Set certificates directory to /etc/kubernetes/ssl

---

CHANGELOG.md
helm/cluster-gcp/templates/_machine_deployments.tpl

If a `machineDeployments` array is provided where each item doesn't contain all keys then the default values from the values.yaml wont be used. This ensures that fallback values are always used if not found in the array.
/test create

Handle incomplete machineDeployments array items

---

CHANGELOG.md
helm/cluster-gcp/templates/_control_plane.tpl

`chart-operator` fails in bootstrap mode because
```
x509: certificate is valid for 172.31.0.1, 10.164.0.6, 34.111.111.50, not 127.0.0.1
```
/test create

Add localhost to certSANs of apiserver certs

---

CHANGELOG.md
helm/cluster-gcp/templates/_bastion.tpl
helm/cluster-gcp/templates/_control_plane.tpl
helm/cluster-gcp/templates/_helpers.tpl
helm/cluster-gcp/templates/_machine_deployments.tpl
helm/cluster-gcp/values.schema.json
helm/cluster-gcp/values.yaml

There are sometimes occasions when the hash suffix generated for immutable resources isn't updated when it needs to be. An example is when the template for that resource changes but not the values being used for that resource.
This update to the hash function allows for forcing a new hash to be generated by setting `.Values.hashSalt` to a random string.
/cc @erkanerol this might also be useful for CAPO / CAPVCD
/test create

Added hashSalt support

---

CHANGELOG.md
helm/cluster-gcp/templates/_control_plane.tpl
helm/cluster-gcp/templates/_machine_deployments.tpl
helm/cluster-gcp/values.yaml

The scopes were being rendered incorrectly like
```
serviceAccounts:
email: capg-controller-manager@puc-f-gs-mgmt-sbx-f706.iam.gserviceaccount.com
scopes:
- https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/ndev.clouddns.readwrite
```
But we want them as an array.

Correctly render SA scopes as array

---

.gitignore
CHANGELOG.md
Makefile.custom.mk
helm/cluster-gcp/templates/_bastion.tpl
helm/cluster-gcp/templates/_control_plane.tpl
helm/cluster-gcp/templates/_machine_deployments.tpl

Updates the usage of the `hash` function to pass in the whole template its related to, rather than just the values. 
This should hopefully avoid all instances where Helm attempts to update immutable values in-place rather than recreating.
/test create

Improve hash function based on whole template

---

CHANGELOG.md
helm/cluster-gcp/templates/_gcp_cluster.tpl

The rename from routeTableId to enableFlowLogs hasn't been released upstream yet. The field has to be set because in the go structs it's of type `*bool` and does not have the `omitempty` json annotation
Co-authored-by: Mario Nitchev <mario@giantswarm.io>
/test create

Set only routeTableId

---

CHANGELOG.md
helm/cluster-gcp/templates/_control_plane.tpl

Towards https://github.com/giantswarm/roadmap/issues/1456
Make kubeadm skip kube-proxy deployment as we will use cilium. It requires CAPI >= `v1.2.0`.

Make kubeadm skip kube-proxy deployment as we will use cilium

---

CHANGELOG.md
helm/cluster-gcp/files/etc/ssh/sshd_config_bastion

towards https://github.com/giantswarm/roadmap/issues/1380
necessary for nested ssh proxy commands to forwards STDIN and STDOUT

allow-tcp-forward-for-bastion

---

CHANGELOG.md
helm/cluster-gcp/values.yaml

:warning: Blocked by https://github.com/giantswarm/cilium-app/pull/44
Towards: https://github.com/giantswarm/roadmap/issues/1324 
* Updates to latest patch release of Kubernetes 1.22
* Switches the base OS to use Ubuntu 22.04
Waiting on image being ready...
/test create

Ubuntu 22.04

---

CHANGELOG.md
helm/cluster-gcp/templates/_control_plane.tpl
helm/cluster-gcp/templates/list.yaml
scripts/pod-test.yaml
scripts/test.sh

Towards https://github.com/giantswarm/giantswarm/issues/24276
With these changes, we don't create the job that updates `coredns` manifests to adopt it as an app. Instead, we tell `kubeadm` not to deploy `coredns`, and later on, the app platform will deploy `coredns` as a default app.
/test create
/test upgrade

Skip kubeadm coredns installation

---

CHANGELOG.md
helm/cluster-gcp/values.yaml

Towards: https://github.com/giantswarm/roadmap/issues/1564
/test create
/test upgrade

Bumped default Kubernetes version to v1.23

---

CHANGELOG.md
helm/cluster-gcp/templates/_control_plane.tpl

Ensures the version value on `KubeadmControlPlane` is always prefixed with a `v` as this value is compared to the version value in the status to work out if nodes need rolling. 
Usually this is ensured by a mutating webhook but if for whatever reason the webhook isn't called (such as we need to work around it for the skipPhases change) then this ensures the control plane isn't endlessly rolling.
/test create
/test upgrade

Ensure version always prefixed

---

CHANGELOG.md
helm/cluster-gcp/templates/_control_plane.tpl
helm/cluster-gcp/templates/_machine_deployments.tpl
helm/cluster-gcp/values.schema.json
helm/cluster-gcp/values.yaml

Fixes https://github.com/giantswarm/roadmap/issues/1587
Supports setting custom taints on both worker nodes and control plane nodes.
Note: does not allow for removing of default taints! (by design)
/test create
/test upgrade

Support setting custom node taints

---

CHANGELOG.md
Makefile.custom.mk
helm/cluster-gcp/ci/ci-values.yaml
helm/cluster-gcp/templates/_control_plane.tpl

There was a problem setting the `baseDomain` last week, and clusters kept being created relying on the default `baseDomain`, which was set to example.com. This made that the clusters were not being created successfully.
Instead, this value should be always be passed and fail if that's not the case.
/test create
/test upgrade

Make 'baseDomain' a required value

---

CHANGELOG.md
helm/cluster-gcp/values.schema.json

Adds `items` schema for `.customNodeTaints`.
This is required for proper validation and generating a data entry form for this app (towards https://github.com/giantswarm/roadmap/issues/1181)
As there are two arrays for custom node taints, the item schema is defined in the `$defs` section and referenced multiple times.
/test create
/test upgrade

Specify `customNodeTaints` items schema

---

CHANGELOG.md
helm/cluster-gcp/values.schema.json

Adds the missing schema for items of the `customNodeLabels` array.
Depends on https://github.com/giantswarm/schema/pull/2
Towards https://github.com/giantswarm/roadmap/issues/1181

Specify items schema for customNodeLabels

---

CHANGELOG.md
helm/cluster-gcp/values.yaml

Towards https://github.com/giantswarm/roadmap/issues/1886
/test create
/test upgrade

bump kubernetes version to v1.23.16

---

CHANGELOG.md
helm/cluster-gcp/values.yaml

Rollback kubernetes version to 1.23.13 as upgrade path is broken.
https://github.com/kubernetes-sigs/cluster-api/issues/7768
https://github.com/kubernetes-sigs/cluster-api/issues/7833
/test create
/test upgrade

Rollback kubernetes version to 1.23.13

---

CHANGELOG.md
helm/cluster-gcp/templates/_control_plane.tpl
helm/cluster-gcp/templates/_helpers.tpl
helm/cluster-gcp/templates/_machine_deployments.tpl

Towards https://github.com/giantswarm/giantswarm/issues/25275
Without these permissions, `node-exporter` fails to retrieve info from the filesystem. Related: https://github.com/giantswarm/cluster-azure/pull/41
/test create
/test upgrade

Set right permissions to /var/lib/kubelet for node-exporter

---

helm/cluster-gcp/values.schema.json

Towards https://github.com/giantswarm/roadmap/issues/2099
This PR applies `schemalint normalize` to the schema. The effect is that key order and white space get normailzed and subsequent PRs will not contain such purely cosmetic changes.
This has no logical effect on the chart.
/test create
/test upgrade

Normalize values schema
