giantswarm/cluster-gcp

CHANGELOG.md, helm/cluster-gcp/templates/_cluster_resource_set.tpl, helm/cluster-gcp/templates/_control_plane.tpl, helm/cluster-gcp/templates/_coredns.tpl, helm/cluster-gcp/templates/_psps.tpl, helm/cluster-gcp/templates/list.yaml, helm/cluster-gcp/values.yaml
Requires: https://github.com/giantswarm/default-apps-gcp/pull/9
=> Re-enabled PSPs

CHANGELOG.md, helm/cluster-gcp/Chart.lock, helm/cluster-gcp/Chart.yaml, helm/cluster-gcp/templates/list.yaml, helm/cluster-gcp/values.yaml
=> Updated cluster-shared library chary

CHANGELOG.md, helm/cluster-gcp/values.yaml
Also move to the europe-west3 region (Germany)
=> Add more machineDeployments in different AZs

CHANGELOG.md, helm/cluster-gcp/templates/_bastion.tpl
Reverts giantswarm/cluster-gcp#49
=> Revert "Add nodeRegistration to bastion KubeadmConfigTempalte"

helm/cluster-gcp/templates/list.yaml, helm/cluster-gcp/values.schema.json, helm/cluster-gcp/values.yaml
=> make-bastion-optional

CHANGELOG.md, helm/cluster-gcp/Chart.lock, helm/cluster-gcp/Chart.yaml, helm/cluster-gcp/templates/_helpers.tpl
=> Bump to latest cluster-shared

.gitignore, CHANGELOG.md, helm/cluster-gcp/Chart.yaml
=> Bump cluster-shared for coredns-workers fix

CHANGELOG.md, helm/cluster-gcp/templates/_helpers.tpl
=> Removed chart label from selector labels

helm/cluster-gcp/Chart.lock, helm/cluster-gcp/Chart.yaml
=> Bump cluster-shared

CHANGELOG.md, helm/cluster-gcp/Chart.lock
=> Bump shared dep to latest

CHANGELOG.md, helm/cluster-gcp/templates/_helpers.tpl, helm/cluster-gcp/values.schema.json, helm/cluster-gcp/values.yaml
The default is still 1804, but we should start testing with 2004.
=> Add value to configure the vm image's ubuntu version

CHANGELOG.md, helm/cluster-gcp/templates/_bastion.tpl, helm/cluster-gcp/templates/_control_plane.tpl, helm/cluster-gcp/templates/_helpers.tpl, helm/cluster-gcp/templates/_machine_deployments.tpl
Ensure immutable resources have unique names (based on the contents of their values) so updates can be made via delete/replace.
~Blocked by https://github.com/giantswarm/config/pull/1146~
~Blocked by https://github.com/giantswarm/deletion-blocker-operator/pull/4~
=> Handle updates to immutable resources

CHANGELOG.md, helm/cluster-gcp/Chart.lock
=> Bump cluster-shared to 0.5.6

CHANGELOG.md, helm/cluster-gcp/templates/_machine_deployments.tpl
Missed a name needing a unique name (and a couple labels that didn't)
=> Added missing hash to template names

CHANGELOG.md, helm/cluster-gcp/templates/_control_plane.tpl, helm/cluster-gcp/templates/_helpers.tpl
add encryption config fro GCP, encryption-provider-operator is already in GCP collection so it should run on gcp MC
=> add-secret-encryption-at-rest

helm/cluster-gcp/templates/_control_plane.tpl, helm/cluster-gcp/templates/_helpers.tpl
tested on gohan finally, apparently secret should not have base64 encoding value set
=> fix-encryption

CHANGELOG.md, Makefile.custom.mk, Makefile.gen.app.mk
I noticed it was accidentally added to the auto-generated one so moved to the correct file.
=> Move custom make targets to correct Makefile

CHANGELOG.md, helm/cluster-gcp/templates/_control_plane.tpl, helm/cluster-gcp/values.schema.json, helm/cluster-gcp/values.yaml
Image now defaults to our retagger'd version.
=> Make etcd image registry customizable

CHANGELOG.md, helm/cluster-gcp/values.yaml
=> Fixed etcd image values

CHANGELOG.md, helm/cluster-gcp/templates/_gcp_cluster.tpl, helm/cluster-gcp/values.schema.json, helm/cluster-gcp/values.yaml
towards https://github.com/giantswarm/giantswarm/issues/22771
=> add-bastion-subnet-whitelist

CHANGELOG.md, helm/cluster-gcp/files/etc/gs-kube-proxy-config.yaml, helm/cluster-gcp/files/opt/gs-kube-proxy-patch.sh, helm/cluster-gcp/templates/_control_plane.tpl, helm/cluster-gcp/templates/_helpers.tpl
=> Expose kube-proxy metrics

CHANGELOG.md, helm/cluster-gcp/templates/_control_plane.tpl, helm/cluster-gcp/values.schema.json, helm/cluster-gcp/values.yaml
Fixes https://github.com/giantswarm/roadmap/issues/1281
=> Removed control plane replicas from values

.github/pull_request_template.md
Towards https://github.com/giantswarm/roadmap/issues/1259
=> Add PR template that triggers e2e tests

CHANGELOG.md, helm/cluster-gcp/templates/_control_plane.tpl, helm/cluster-gcp/templates/_machine_deployments.tpl
Reverts #122 because it breaks MC creation
/test create
=> Revert 'Set certificates directory to /etc/kubernetes/ssl (#122)'

CHANGELOG.md, helm/cluster-gcp/templates/_machine_deployments.tpl, helm/cluster-gcp/values.schema.json, helm/cluster-gcp/values.yaml
We want to be able to choose the SA used by worker nodes.
/test create
=> Allow to choose the Google Service Account for workers

helm/cluster-gcp/templates/_gcp_cluster.tpl, helm/cluster-gcp/values.schema.json, helm/cluster-gcp/values.yaml
Part of giantswarm/roadmap#1196
/test create
=> Add api allow list annotation and helm value

CHANGELOG.md, helm/cluster-gcp/templates/_bastion.tpl, helm/cluster-gcp/templates/_control_plane.tpl, helm/cluster-gcp/templates/_gcp_cluster.tpl, helm/cluster-gcp/templates/_machine_deployments.tpl, helm/cluster-gcp/values.schema.json, helm/cluster-gcp/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/1284
These changes require this PR https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/677
=> Always create single subnet

CHANGELOG.md, helm/cluster-gcp/templates/_control_plane.tpl
Towards https://github.com/giantswarm/roadmap/issues/1347
/test create
=> Pass required flags to controller manager so that pods CIDR can be custom

CHANGELOG.md, helm/cluster-gcp/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/1347
/test create
=> Use different CIDRs for pods and nodes

CHANGELOG.md, helm/cluster-gcp/values.yaml
The values were redundant since they're now in the capg operator.
/test create
=> Change Allowlist defaults to empty string

helm/cluster-gcp/files/etc/kubernetes/gcp.conf, helm/cluster-gcp/templates/_helpers.tpl
Towards https://github.com/giantswarm/roadmap/issues/1356
/test create
=> Add networking information to k8s cloud config file

CHANGELOG.md, helm/cluster-gcp/templates/_bastion.tpl, helm/cluster-gcp/templates/_gcp_cluster.tpl, helm/cluster-gcp/templates/_machine_deployments.tpl
=> Fix helm values cycle

CHANGELOG.md, helm/cluster-gcp/templates/_gcp_cluster.tpl, helm/cluster-gcp/values.schema.json, helm/cluster-gcp/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/1218
/test create
=> Add proxy subnet

CHANGELOG.md, helm/cluster-gcp/templates/_gcp_cluster.tpl
This was change in capg v1.2.0
/test create
=> Use enableFlowLogs instead of routeTableId

helm/cluster-gcp/Chart.yaml
towards https://github.com/giantswarm/roadmap/issues/1448
=> add-annotation-app-type

CHANGELOG.md, Makefile.custom.mk, helm/cluster-gcp/Chart.lock, scripts/test.sh
Co-authored-by: George Gelaga-King <gb7309@gmail.com>
/test create
=> Bump cluster-shared to v0.6.3

helm/cluster-gcp/Chart.lock, helm/cluster-gcp/Chart.yaml
Updated to match what is actually used in Chart.lock.
/test create
/test upgrade
=> Update version in Chart.yaml

CHANGELOG.md
Attempts to improve a changelog entry, as an example on how to make it more self-explanatory, and to establish best practices.
- Adding missing info for v0.30.2
- Little language changes
=> Some changelog improvements

CHANGELOG.md, helm/cluster-gcp/Chart.lock, helm/cluster-gcp/Chart.yaml
=> Bumped cluster-shared for coredns-adopter polling fix
